process.env.PGHOST="localhost"
process.env.PGPORT="5432"
process.env.PGDATABASE="nextshop"
process.env.PGUSERNAME="postgres"
process.env.PGPASSWORD="admin"
process.env.PGIDLE_TIMEOUT=".1"
process.env.PGCONNECT_TIMEOUT=".5"

export const validTestProduct = {
		name:"__TEST__",
		description:"This is test",
		price:220,
		brand:"Sit",
		category:"Laptops"
}
export const validTestUser = {
	name:"TEST__",
	passwordHash:"e172c5654dbc12d78ce1850a4f7956ba6e5a3d2ac40f0925fc6d691ebb54f6bf",
}
export const validTestOrder = {
	user:1,
	order:{1:{amount:1,price:1}},
	status:"PROCESSING"
}
export const validTestDiscount = {
	discount:50,
	brands:["Sit"],
	categories:["Laptops"],
	expires:Date.now()+100000
}

export const validProducts = [
{"name":"amet eu dapibus.","description":"Nunc magna diam, bibendum sit amet urna sed, lobortis tempus nisi. Praesent vitae sagittis enim. Aliquam facilisis nisi id dui malesuada, vitae ultricies nisi ullamcorper. Aliquam augue tortor, egestas non erat eu, pellentesque ullamcorper diam. Suspendisse posuere laoreet metus vitae gravida. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec feugiat non mi a convallis. Mauris mollis, dui at volutpat pretium, metus diam dictum felis, sed pellentesque tortor lorem at nibh.\n\nSuspendisse et lectus neque. Nunc ut arcu efficitur libero dapibus fermentum id vitae ex. Fusce pellentesque euismod orci ut maximus. Morbi et bibendum orci. Curabitur tincidunt diam sed sem faucibus, ac ornare mauris tempor. Duis dignissim quam eu purus dignissim, ut facilisis nibh tristique. Morbi ut dignissim ante, ut aliquet tellus. Nullam ut tincidunt lorem. Ut sit amet turpis faucibus, vestibulum lectus vel, hendrerit purus. Ut eu nunc nibh. Pellentesque interdum dolor dignissim nibh bibendum, sed egestas neque maximus.","images":["741f82f3.jpg","0ebbd635.jpg"],"price":381.52,"id":272,"brand":77,"category":8,"votes":0,"voters":0,"rating":null},
 {"name":"accumsan facilisis","description":"Pellentesque molestie efficitur tortor, vel cursus ex bibendum vitae. Duis egestas ultrices eros, ac laoreet lectus accumsan et. Etiam porttitor eleifend ultrices. Vivamus vestibulum sagittis eros vel vehicula. Nullam non nunc in nibh lacinia cursus. Nam non nulla scelerisque, posuere leo eu, ultricies arcu. Suspendisse congue congue bibendum. Mauris faucibus interdum eros, lacinia egestas nisi interdum quis. Pellentesque viverra dui sit amet erat convallis, sit amet consequat lacus tempor. Sed facilisis nisi ut arcu ultrices hendrerit molestie a massa. Sed faucibus non mi non eleifend. Maecenas faucibus, ipsum at vehicula faucibus, diam nibh placerat augue, non efficitur leo est non est.\n\nAliquam erat volutpat. Suspendisse sit amet libero in ex vulputate porttitor id ut ex. Vivamus at posuere odio, id sodales ipsum. Suspendisse potenti. Mauris et tellus eu turpis condimentum fermentum sit amet id est. Nam eleifend lectus quis massa semper, quis laoreet mi lacinia. Nullam in eros tincidunt, feugiat ante a, mattis ex. Phasellus eget mollis magna. Donec consectetur arcu nec dolor fermentum faucibus.\n\nProin ut neque dolor. In sit amet dictum justo. Cras magna sem, dictum non massa in, ultricies bibendum ipsum. Pellentesque eu ligula neque. Nullam lacinia odio risus, quis efficitur odio viverra pharetra. Nullam luctus convallis varius. Cras congue dictum ipsum, a viverra ex fermentum vestibulum.","images":["3380678d.jpg","5f11cfc7.jpg","4f185179.jpg","3c7493b1.jpg"],"price":1647.26,"id":273,"brand":80,"category":8,"votes":0,"voters":0,"rating":null},
 {"name":"Etiam volutpat.","description":"Nulla facilisi. Aliquam erat volutpat. Phasellus dapibus est in turpis congue, nec suscipit nulla luctus. Nunc euismod metus turpis, vitae accumsan erat scelerisque sit amet. Aliquam justo lacus, sagittis non euismod sit amet, consequat id nibh. Maecenas ut nulla neque. Donec at facilisis erat. Donec a massa sem. Integer nec purus a mi rhoncus aliquet.\n\nNam laoreet metus nec ante maximus cursus. Proin id pharetra lorem. Duis varius est ut erat tempus, sed semper augue porta. Ut et imperdiet quam. Maecenas at commodo ante. Sed ornare enim at sagittis eleifend. Integer pretium auctor turpis. Praesent a metus sit amet sem imperdiet rutrum ac vitae nibh.\n\n\n\nNam pretium, lorem ac iaculis gravida, purus odio accumsan odio, sed feugiat ligula ante et lacus. In quis leo nisi. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam vel mattis ipsum, ac tincidunt velit. Nunc gravida lacus in orci sollicitudin viverra. Vestibulum dolor mi, cursus nec ornare eget, cursus ac purus. Vestibulum non odio ligula. Ut dapibus ultrices odio, vel pellentesque nisl euismod non.\n\nAliquam erat volutpat. Suspendisse sit amet libero in ex vulputate porttitor id ut ex. Vivamus at posuere odio, id sodales ipsum. Suspendisse potenti. Mauris et tellus eu turpis condimentum fermentum sit amet id est. Nam eleifend lectus quis massa semper, quis laoreet mi lacinia. Nullam in eros tincidunt, feugiat ante a, mattis ex. Phasellus eget mollis magna. Donec consectetur arcu nec dolor fermentum faucibus.","images":["b6d8ed83.jpg","16c63fa7.jpg"],"price":952.56,"id":274,"brand":76,"category":8,"votes":0,"voters":0,"rating":null},
 {"name":"et viverra congue","description":"Pellentesque molestie efficitur tortor, vel cursus ex bibendum vitae. Duis egestas ultrices eros, ac laoreet lectus accumsan et. Etiam porttitor eleifend ultrices. Vivamus vestibulum sagittis eros vel vehicula. Nullam non nunc in nibh lacinia cursus. Nam non nulla scelerisque, posuere leo eu, ultricies arcu. Suspendisse congue congue bibendum. Mauris faucibus interdum eros, lacinia egestas nisi interdum quis. Pellentesque viverra dui sit amet erat convallis, sit amet consequat lacus tempor. Sed facilisis nisi ut arcu ultrices hendrerit molestie a massa. Sed faucibus non mi non eleifend. Maecenas faucibus, ipsum at vehicula faucibus, diam nibh placerat augue, non efficitur leo est non est.","images":["faa72fb8.jpg","427feac4.jpg","84f6c467.jpg","c0b5cabc.jpg","9f077fce.jpg"],"price":96.9,"id":263,"brand":78,"category":7,"votes":2,"voters":1,"rating":2},
 {"name":"neque. nulla pharetra.","description":"Etiam quis est et felis mollis rhoncus vel non lorem. Aliquam scelerisque orci in orci facilisis sagittis. Integer et nibh in orci consectetur mollis. Nulla mattis libero non mauris gravida luctus. Nunc vel neque a est ullamcorper ullamcorper. Morbi vitae ante blandit, consequat nisl quis, dignissim ipsum. In sed massa sagittis, eleifend neque sit amet, vestibulum dolor.\n\nSuspendisse eu quam elit. Quisque sem est, posuere rutrum augue sit amet, rhoncus mollis felis. Proin facilisis id odio eget bibendum. Suspendisse felis neque, bibendum vel interdum ut, dapibus sit amet nibh. Vivamus sagittis nec massa sit amet porta. Nullam pretium, ligula vitae tincidunt dictum, leo tortor porta dui, volutpat maximus risus urna quis lectus. Quisque accumsan feugiat volutpat. Donec dignissim sagittis imperdiet. Proin dapibus, eros eget posuere sodales, arcu justo efficitur lacus, quis rutrum felis risus id leo. Donec tincidunt efficitur ex dictum ultricies.\n\nSuspendisse potenti. Nam a dolor arcu. Vestibulum at venenatis turpis. Vestibulum pellentesque tempor viverra. Proin facilisis eget arcu et pulvinar. Integer molestie, eros id mollis auctor, lectus erat tempor massa, non commodo orci neque vitae magna. Nunc dictum dui nec urna bibendum, porttitor convallis sem consectetur. Suspendisse rutrum consequat eros, sed sollicitudin neque blandit eget.","images":["262e9854.jpg","ac2a79ac.jpg"],"price":140.99,"id":275,"brand":78,"category":7,"votes":0,"voters":0,"rating":null},
 {"name":"metus. ultrices.","description":"Suspendisse potenti. Nam a dolor arcu. Vestibulum at venenatis turpis. Vestibulum pellentesque tempor viverra. Proin facilisis eget arcu et pulvinar. Integer molestie, eros id mollis auctor, lectus erat tempor massa, non commodo orci neque vitae magna. Nunc dictum dui nec urna bibendum, porttitor convallis sem consectetur. Suspendisse rutrum consequat eros, sed sollicitudin neque blandit eget.","images":["03d6d859.jpg","00475c4f.jpg","b4e9a080.jpg","439da7bc.jpg","92b0eb19.jpg"],"price":546.41,"id":279,"brand":77,"category":8,"votes":0,"voters":0,"rating":null},
 {"name":"faucibus vel ante","description":"Nam pretium, lorem ac iaculis gravida, purus odio accumsan odio, sed feugiat ligula ante et lacus. In quis leo nisi. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam vel mattis ipsum, ac tincidunt velit. Nunc gravida lacus in orci sollicitudin viverra. Vestibulum dolor mi, cursus nec ornare eget, cursus ac purus. Vestibulum non odio ligula. Ut dapibus ultrices odio, vel pellentesque nisl euismod non.\n\nMauris ullamcorper ipsum non urna semper, at luctus massa imperdiet. Donec commodo rhoncus vestibulum. Praesent semper vestibulum nunc, eu laoreet ante porta non. Vivamus pellentesque commodo tellus in porttitor. Mauris libero velit, ultrices eu iaculis in, vulputate ac purus. Pellentesque a turpis vitae quam molestie porttitor vitae quis velit. Aliquam accumsan nibh sit amet felis malesuada, quis lobortis turpis dapibus. Suspendisse vel imperdiet nunc, in feugiat urna. Mauris vitae sagittis metus. Integer consequat vehicula quam et fermentum. Integer cursus elit eros, in pretium velit molestie quis. Donec vehicula, libero ut rhoncus volutpat, nisi felis egestas justo, eget laoreet arcu odio sed ex. Nullam cursus efficitur enim, vitae fermentum quam congue at. Proin tortor diam, suscipit et tellus id, finibus consequat ipsum. Sed eget aliquet turpis, sit amet placerat diam. Cras tempus sapien est, nec placerat odio laoreet vitae.\n\nSuspendisse et lectus neque. Nunc ut arcu efficitur libero dapibus fermentum id vitae ex. Fusce pellentesque euismod orci ut maximus. Morbi et bibendum orci. Curabitur tincidunt diam sed sem faucibus, ac ornare mauris tempor. Duis dignissim quam eu purus dignissim, ut facilisis nibh tristique. Morbi ut dignissim ante, ut aliquet tellus. Nullam ut tincidunt lorem. Ut sit amet turpis faucibus, vestibulum lectus vel, hendrerit purus. Ut eu nunc nibh. Pellentesque interdum dolor dignissim nibh bibendum, sed egestas neque maximus.\n\nProin ut neque dolor. In sit amet dictum justo. Cras magna sem, dictum non massa in, ultricies bibendum ipsum. Pellentesque eu ligula neque. Nullam lacinia odio risus, quis efficitur odio viverra pharetra. Nullam luctus convallis varius. Cras congue dictum ipsum, a viverra ex fermentum vestibulum.","images":["77c644b2.jpg","2576aa7c.jpg","3a806399.jpg","fd63a437.jpg","e4f5e21b.jpg"],"price":1983.86,"id":281,"brand":77,"category":8,"votes":0,"voters":0,"rating":null},
 {"name":"nibh arcu. turpis.","description":"Aenean posuere justo vitae elit convallis consequat. In hac habitasse platea dictumst. Vivamus id libero urna. Vivamus cursus pretium tellus, et ornare quam fermentum non. Cras lacus urna, commodo sed massa a, facilisis elementum sem. Nullam rutrum, nibh sed malesuada vulputate, ipsum nibh cursus est, vehicula elementum ipsum eros sit amet sapien. Pellentesque rhoncus, purus eget faucibus gravida, turpis massa consequat lacus, volutpat varius velit odio eu libero. Donec eu mattis nisi, at laoreet felis. Sed accumsan volutpat ante. Vivamus vitae pharetra dui. Nulla facilisi. Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus at commodo nunc, vitae venenatis massa. Nunc tortor massa, vulputate et pharetra non, ultrices sit amet leo. Praesent quam ipsum, gravida nec venenatis quis, tempus id velit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.","images":["fe2828ce.jpg"],"price":420.83,"id":277,"brand":77,"category":6,"votes":0,"voters":0,"rating":null},
 {"name":"Vivamus odio. dapibus","description":"Suspendisse eu quam elit. Quisque sem est, posuere rutrum augue sit amet, rhoncus mollis felis. Proin facilisis id odio eget bibendum. Suspendisse felis neque, bibendum vel interdum ut, dapibus sit amet nibh. Vivamus sagittis nec massa sit amet porta. Nullam pretium, ligula vitae tincidunt dictum, leo tortor porta dui, volutpat maximus risus urna quis lectus. Quisque accumsan feugiat volutpat. Donec dignissim sagittis imperdiet. Proin dapibus, eros eget posuere sodales, arcu justo efficitur lacus, quis rutrum felis risus id leo. Donec tincidunt efficitur ex dictum ultricies.\n\nProin ut neque dolor. In sit amet dictum justo. Cras magna sem, dictum non massa in, ultricies bibendum ipsum. Pellentesque eu ligula neque. Nullam lacinia odio risus, quis efficitur odio viverra pharetra. Nullam luctus convallis varius. Cras congue dictum ipsum, a viverra ex fermentum vestibulum.\n\nNulla facilisi. Aliquam erat volutpat. Phasellus dapibus est in turpis congue, nec suscipit nulla luctus. Nunc euismod metus turpis, vitae accumsan erat scelerisque sit amet. Aliquam justo lacus, sagittis non euismod sit amet, consequat id nibh. Maecenas ut nulla neque. Donec at facilisis erat. Donec a massa sem. Integer nec purus a mi rhoncus aliquet.\n\nPellentesque nisl eros, pellentesque eu augue eget, dapibus laoreet ex. Maecenas vitae turpis sollicitudin dui tincidunt venenatis. Vivamus vehicula nisi ut turpis laoreet, eu dictum tortor convallis. Ut vitae egestas urna. Proin suscipit sem et mattis aliquet. Ut egestas lobortis risus et faucibus. Curabitur hendrerit maximus dui, eget luctus mi ultrices ac.","images":["9968401e.jpg","267375cf.jpg","6debffee.jpg"],"price":822.49,"id":282,"brand":80,"category":6,"votes":0,"voters":0,"rating":null},
 {"name":"Cras ex Donec in","description":"Pellentesque nisl eros, pellentesque eu augue eget, dapibus laoreet ex. Maecenas vitae turpis sollicitudin dui tincidunt venenatis. Vivamus vehicula nisi ut turpis laoreet, eu dictum tortor convallis. Ut vitae egestas urna. Proin suscipit sem et mattis aliquet. Ut egestas lobortis risus et faucibus. Curabitur hendrerit maximus dui, eget luctus mi ultrices ac.\n\nEtiam sit amet posuere libero. Curabitur faucibus tempor nisl, in congue lacus lacinia vel. Sed in pharetra massa. Etiam id purus nunc. Quisque volutpat lorem maximus tincidunt semper. Vivamus vitae urna felis. Morbi imperdiet metus in porta ornare. Donec sed placerat urna. Duis tempus nisi eros, in gravida nunc tristique eget. Duis euismod tincidunt libero. Donec dui tortor, iaculis eget ornare a, tristique a leo. Quisque eu ex id nisi efficitur blandit. Duis ultricies, purus vel mattis viverra, purus neque sodales velit, et lacinia tellus elit vitae velit.","images":["9b8a658d.jpg","f5485393.jpg","19f2ec14.jpg","0b675dd2.jpg"],"price":654.05,"id":283,"brand":79,"category":8,"votes":0,"voters":0,"rating":null},
]

