services:
  db:
    image: postgres
    restart: always
    tmpfs:
      - /var/lib/postgresql/data
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - ${PGPORT}:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
